### ISSUE TITLE
Docs do not address how to open services for images

### ISSUE THREAD

**Issue by patientplatypus** [oracle/terraform-kubernetes-installer#109]
So these docs appear to be incomplete - at least from a beginner standpoint. I can stand up the service, get the cluster up and running and even use the example code provided here: https://www.terraform.io/docs/providers/kubernetes/guides/getting-started.html ie: 
```
resource "kubernetes_pod" "nginx" {
  metadata {
    name = "nginx-example"
    labels {
      App = "nginx"
    }
  }

  spec {
    container {
      image = "nginx:1.7.8"
      name  = "example"

      port {
        container_port = 80
      }
    }
  }
}
```

To stand up a pod. 

**However**

I cannot use the example code linked to above to create a service that will expose this pod because we already have a load balancer in this boiler plate. I cannot use `kubectl expose` as far as I am aware to expose this service. 

At this point I am not sure if the problems I am having are because the ports are not configured correctly in the boilerplate out of the box, I am not using kubectl expose correctly, or if the Oracle cloud firewall or security settings are misconfigured.

Would it be possible to link to a simple example on how to get images to run on this? Otherwise it is difficult/impossible for me to use.

**Comment by jlamillan** [comment]
Using the cluster is a bit out of scope, but here is the `kubectl` commands I would use to run / expose nginx after spinning up a cluster:

1. First, create a Deployment (with three pod replicas in this case)

```
kubectl run nginx --image=nginx --port=80 --replicas=3
```

Now, to expose nginx as a service, you can either create a service of type `LoadBalancer` or of type `NodePort`. The former will create an OCI load balancer whose IP you will use to access the service. The latter will expose a port on your nodes. 

2a. If you chose, LoadBalancer

```
kubectl  expose deployment nginx --type LoadBalancer
```
The IP address in the `EXTERNAL-IP` column is the IP of your OCI load balancer and what you use to access the service (in this case 129.214.55.10, which routes to port 31723 on the node).   Note that it will be in the `<pending>` state while the OCI load balancer is being provisioned.

```
kubectl  get service nginx

NAME         TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
nginx        LoadBalancer   10.21.235.206   129.214.55.10   80:31723/TCP   3m
```
```
curl 129.214.55.10

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```

2b. Instead of an OCI LB, if you just want to expose the service on your worker nodes, run the following command:
```
kubectl expose deployment nginx --type NodePort
```

```
kubectl  get nodes -o wide 
NAME                                                 STATUS    ROLES     AGE       VERSION   EXTERNAL-IP      OS-IMAGE                  KERNEL-VERSION                   CONTAINER-RUNTIME
k8s-worker-ad2-0.k8sworkerad2.k8soci.oraclevcn.com   Ready     <none>    5h        v1.7.10   129.213.64.144   Oracle Linux Server 7.4   4.1.12-112.14.10.el7uek.x86_64   docker://Unknown
```
And access the allocated service port directly on the node IP (in this case, port 31723):

```
curl 129.213.64.144:31723

<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
