### ISSUE TITLE
oci_core_images OCID lookup failing

### ISSUE THREAD

**Issue by derekoneil** [oracle/terraform-kubernetes-installer#188]
### Terraform Version

<details>
Terraform v0.11.6

+ provider.null v1.0.0
+ provider.oci v2.1.3
+ provider.random v1.1.0
+ provider.template v1.0.0
+ provider.tls v1.0.1
</details>

### OCI Provider Version

<details>
2.1.3
</details>

### Terraform Installer for Kubernetes Version

<details>
1.3.0
</details>

### Description of issue:

Running 'terraform plan' fails with an error trying to look up the OCID of the base linux image to use for each of the instances (etcd, master, worker). The error message is: 

```
Error: Error running plan: 1 error(s) occurred:

* module.instances-etcd-ad1.oci_core_instance.TFInstanceEtcd: 1 error(s) occurred:

* module.instances-etcd-ad1.oci_core_instance.TFInstanceEtcd: At column 47, line 1: list "data.oci_core_images.ImageOCID.images" does not have any elements so cannot determine type. in:

${lookup(data.oci_core_images.ImageOCID.images[0], "id")}
```

This only started happening recently -- up until this week the same setup (input variables, OCI tenants, installer version, etc) has worked successfully. The error happens on multiple machines and in multiple OCI tenants (though all are in Ashburn).

Replacing the image lookup `${lookup(data.oci_core_images.ImageOCID.images[0], "id")}` in each instance's main.tf file with the actual OL7.4 OCID obtained from the OCI console `ocid1.image.oc1.iad.aaaaaaaajlw3xfie2t5t52uegyhiq2npx7bqyu4uvi2zyu3w3mqayc2bxmaa` resolves the error and allows terraform plan to complete successfully. 

I'm happy to provide any additional info that would help.

**Comment by garthy** [comment]
This is probably due to images being updated/retired by OCI and we need to update the default image reference.

**Comment by beide** [comment]
I got these error since Friday. I found a workaround. if you go to the instances directory and in each intance folder for example k8smaster. Change the content of datasources.tf  like the following 
data "oci_core_images" "ImageOCID" {
  compartment_id = "${var.compartment_ocid}"
  #display_name   = "${var.oracle_linux_image_name}"
  operating_system = "Oracle Linux"
  operating_system_version = "7.4"

}
Bascially, I comment out the display_name and add the two lines afterward. It works for me.

**Comment by garthy** [comment]
Fixed by https://github.com/oracle/terraform-kubernetes-installer/pull/190
