### ISSUE TITLE
Documentation Wrong

### ISSUE THREAD

**Issue by patientplatypus** [oracle/terraform-kubernetes-installer#97]
Notice that here https://github.com/oracle/terraform-provider-oci

On *nix
~/.terraform.d/plugins/
Then create the ~/.terraformrc file that specifies the path to the oci provider **(only required for v0.9.x).**

providers {
  oci = "~/.terraform.d/plugins/terraform-provider-oci"
}

It has a caveat, whereas here

Prerequisites

Create an Terraform configuration file at ~/.terraformrc that specifies the path to the OCI provider:
providers {
  oci = "<path_to_provider_binary>/terraform-provider-oci"
}

It does not. 

I am assuming that the first one is correct as it is more up to date, but then this one needs to be fixed. Thanks.

**Comment by jlamillan** [comment]
Thanks for the feedback. After reading some background on this, I'm not sure the documentation is _wrong_.  Rather, there are [multiple ways](https://github.com/hashicorp/terraform/issues/15705) for specifying the third-party plugin path and making it available to the scripts. 

I prefer the current approach since we don't want to be responsible for bundling different versions and builds of a plugin in this repo since the providers have their own versions and releases. So, `terraform-kubernetes-installer/terraform.d` doesn't seem like the best way either.

IMO, it'd be best to either leave it like it is, or
